encoding: utf-8
timezone: America/Vancouver
remote_theme: jekyll/minima
show_excerpts: true
title: Coding as Life
description: Random posts about programming and productivity
permalink: /:categories/:title:output_ext
author:
  name: Yuki Sato
  email: yuki.sato.dev@gmail.com
url: https://yukisato.github.io
baseurl: /blog

minima:
  skin: solarized
  # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize date format
  date_format: "%b %-d, %Y"

  social_links:
    twitter: yukisato_dev
    github: yukisato
    linkedin: yuki-sato

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
      type: posts
    values:
      layout: post
      author: Yuki Sato

google_analytics: G-VGG522PKMD
plugins:
  - jekyll-sitemap
